name: base_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  dio_helper: ^1.1.0
  tf_custom_widgets: ^1.0.25
  tf_validator: ^0.0.2
  auto_route:  ^3.2.4
  flutter_local_notifications: ^9.1.2
  shared_preferences: ^2.0.8
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.12
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0
#  page_view_indicator: ^2.0.4
  location: ^4.3.0
  photo_view: ^0.13.0
  intl: ^0.18.1
  flutter_easyloading: ^3.0.3
  flutter_phoenix: ^1.0.0
  #flutter_swiper: any
  carousel_slider: ^4.0.0
  share: ^2.0.4
  flutter_rounded_date_picker: ^3.0.4
  material_design_icons_flutter: ^5.0.6295
  map_launcher: ^2.1.1
  flutter_html: ^3.0.0-beta.2
  pin_code_fields: ^7.3.0
  image_picker: ^0.8.4+4
  flutter_svg: ^0.23.0+1
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  lottie: ^1.2.1
  dots_indicator: ^2.0.0
  dotted_border:
  flutter_rating_bar: ^4.0.0
  animations: ^2.0.2
  flip_card: ^0.6.0
  draggable_fab: any
  expandable: ^5.0.1
  signalr_core: ^1.1.1
  liquid_pull_to_refresh: ^3.0.0
  infinite_scroll_pagination: ^3.0.1+1
  flutter_speed_dial: ^4.6.6
  curved_navigation_bar: ^1.0.1
  google_maps_flutter: ^2.0.11
  geolocator:
  geocoding: ^2.2.0
  google_fonts: ^4.0.4
#  geocoder:








flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route: ^3.2.4
  build_runner: ^2.4.8
#  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/anim/api_empty.json
    - assets/anim/api_error.json
    - assets/anim/delivery.json
    - assets/anim/empty_cart.json
    - assets/anim/success.json
    - assets/fonts/MyFlutterApp.ttf
    - assets/images/apple_pay.png
    - assets/images/arabic.png
    - assets/images/benghal.png
    - assets/images/call.png
    - assets/images/credit_card.png
    - assets/images/delivery_amico.png
    - assets/images/done.png
    - assets/images/egypt.png
    - assets/images/english.png
    - assets/images/following.png
    - assets/images/free_shipping_amico.png
    - assets/images/hands.png
    - assets/images/icon.png
    - assets/images/india.png
    - assets/images/logo.png
    - assets/images/logoWhite.png
    - assets/images/mada_Logo.png
    - assets/images/mail.png
    - assets/images/marker.png
    - assets/images/master_card.png
    - assets/images/money.png
    - assets/images/nodata.png
    - assets/images/online.png
    - assets/images/payment.png
    - assets/images/pdf.png
    - assets/images/placeholder.png
    - assets/images/plus.png
    - assets/images/sadad_logo.png
    - assets/images/saudi.png
    - assets/images/splash.png
    - assets/images/urdu.png
    - assets/images/visa.png
    - assets/images/wallet.png
    - assets/images/whatsapp.png
    - assets/lang/ar.json
    - assets/lang/bn.json
    - assets/lang/en.json
    - assets/lang/hi.json
    - assets/lang/ur.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
